pkg/builder.go, pkg/git/git.go, pkg/sshd/server.go, pkg/utils.go
=> doc(builder.go,git.go,server.go,utils.go): adding proper godoc

Makefile
- adding go test to test target
- removing build target from docker-build
- deleting the service on kube-clean
replaces part of #9
=> fix(Makefile): change VERSION, add and fix targets

.travis.yml, Makefile, _scripts/deploy.sh
There are two semantic changes in this PR, both involving the travis build. See below for details.
- make travis run the `build` target before `docker-build` so that necessary binaries get copied into docker image (no more `/entrypoint.sh: line 5: exec: builder: not found` errors on the `quay.io/deisci/builder:v2-alpha` image)
- also switch to using the dev image to run `go` and `glide`. this change allows us to greatly simplify the `.travis.yml` file, including using `language: generic`
Fixes #23 
cc/ @mboersma
=> fix(*): fix travis build

manifests/deis-builder-rc.yaml, rootfs/etc/confd/templates/builder
builder looks at the following environment variables (in order) to determine where to store tarballs, and where to tell slugbuilders to look:
1. `$DEIS_MINIO_SERVICE_HOST` and `$DEIS_MINIO_SERVICE_PORT`
2. `$DEIS_OUTSIDE_STORAGE_HOST` and `$DEIS_OUTSIDE_STORAGE_PORT`
3. otherwise it falls back to the fetcher, which is a REST API for the the local filesystem (to be removed in a future patch. see #6)
if an operator launches a builder with this environment variable and does not have a minio service running, builder will do the following:
1. use the mc tool to upload the tarball to
`http://$DEIS_OUTSIDE_STORAGE_HOST:${DEIS_OUTSIDE_STORAGE_PORT}`
2. Instantiate a slugbuilder with TAR_URL the same as above
~~still needs to deal with the self signed cert for minio~~ _we've decided not to run …
=> feat(builder): add support for external object storage

rootfs/etc/deis-slugbuilder.yaml
so the builder script can replace it with the git sha, and no collisions occur
Fixes #41
=> fix(deis-slugbuilder.yaml): use repo_name instead of deis-slugbuilder

manifests/deis-builder-rc.yaml
not marking showstopper because it's correct in the [helm chart](https://github.com/deis/charts/blob/master/deis/manifests/deis-builder-rc.yaml)
=> fix(deis-builder-rc.yaml): fix indentation on deis-builder RC

rootfs/etc/confd/templates/builder, rootfs/etc/deis-slugbuilder.yaml
=> fix(builder): print buildpack output, decrease verbosity

rootfs/etc/confd/templates/builder
Without these messages, the user may have to wait for a while before the builder pod spins up and the slug runner spins up (respectively).
This is an optional patch for `v2.0-alpha1`.
Fixes #64
=> fix(builder): add status messages

manifests/deis-builder-rc.yaml, rootfs/Dockerfile
We have to set it so the minio client (https://github.com/minio/mc) works properly. Also, we can remove it in the RC manifest because it’s already in the Dockerfile.
The env var can also be removed from [deis/charts](https://github.com/deis/charts/blob/master/deis/manifests/deis-builder-rc.yaml#L30) once this is merged, but since it's redundant it's not a hard requirement for this PR.
=> fix(Dockerfile,deis-builder-rc.yaml): add DOCKERIMAGE env var

rootfs/etc/confd/templates/builder
in builder script we are doing ```git archive --format=tar.gz ${GIT_SHA} > ${APP_NAME}.tar.gz``` twice which is not necessary. Removing the second command
=> feat(builder): remove extra git archive tar

pkg/gitreceive/build.go, pkg/gitreceive/git/sha.go, pkg/gitreceive/git/sha_test.go, pkg/gitreceive/storage/slug_builder_info.go, pkg/gitreceive/storage/slug_builder_info_test.go
and representing the git sha in a struct to do so
Fixes #130 
Makes progress on #132
=> ref(build.go): pulling slugbuilder storage params out

pkg/gitreceive/build.go
The controller now expects builder to send the *entire* slug URL to it. It then forwards that URL to the slugrunner that it launches.
This makes builder compatible with the changes in https://github.com/deis/workflow/pull/346
=> fix(pkg/gitreceive/build.go): send the entire slug URL to the controller

rootfs/Dockerfile
There’s no reason I know of to separate some commands into another
layer. Also, move some ENVs and port expositions to the top, as they’re
almost never changed as well.
Depends on #173 before merge, since that will introduce Dockerfile tests into branch tests.
=> ref(rootfs/Dockerfile): consolidate RUN command

Makefile, boot.go, glide.lock, glide.yaml, manifests/deis-builder-rc.yaml, manifests/deis-builder-service.yaml, pkg/builder.go, pkg/healthsrv/buckets_lister.go, pkg/healthsrv/circuit_state.go, pkg/healthsrv/healthz_handler.go, pkg/healthsrv/healthz_handler_test.go, pkg/healthsrv/namespace_lister.go, pkg/healthsrv/server.go, pkg/sshd/circuit.go, pkg/sshd/circuit_test.go, pkg/sshd/config.go, pkg/sshd/server.go, pkg/sshd/server_test.go, rootfs/Dockerfile
Fixes #92 
Fixes #89 
Ref deis/deis#4809
When this is done, merge deis/charts#93
- Added a health check server with a single endpoint (`/healthz`), intended to be used by the `livenessProbe` and `readinessProbe`.
- This endpoint checks the accessibility of the Kubernetes API & the object storage system, and checks that the SSH server is ready to serve
- The health check server utilizes two `interface`s - for S3 interaction and Kubernetes API interaction - so that those two components can be mocked and the server can be more easily unit tested
- The handler for the `/healthz` endpoint does all three checks concurrently, and only fails if one or more of them don't complete before a hard-coded timeout, or any of them fail before the timeout
- Added a …
=> fix(*): add readiness & liveness probes

pkg/gitreceive/storage/endpoint.go
Directly set outside storage URL . example 
```
- name: "DEIS_OUTSIDE_STORAGE"
value: "https://storage.googleapis.com"
```
first preference to S3 endpoint then minio
=> feat(storage): change outside storage settings

boot.go, pkg/builder.go, pkg/cleaner/cleaner.go, pkg/cleaner/cleaner_test.go, pkg/k8s/namespace.go, pkg/sshd/config.go, pkg/sshd/lock.go, pkg/sshd/server.go, pkg/sshd/server_test.go
This PR introduces a background goroutine that polls the Kubernetes API for the list of namespaces and compares those names with those in its local git folder. The cleaner then deletes all directories that exist locally but not in the namespace list.
To test, follow these steps:
1. Create an app and `git push` to it from repository A
2. `deis apps:destroy -a your_app`
3. Wait at least the polling interval (the default is 1 second)
4. Re-create an app of the same name from repository B (so that the `deis` tool creates the same remote in repo B). Make sure repository B has a different set of refs from A
5. `git push` from repo B
The push should be successful and the app should run properly.
Still TODO:
Notes:
- This PR also introduces global locks on `git push`es, effectively removing some …
=> fix(boot.go,pkg/*): implement a deleted app cleaner

pkg/sshd/config.go
We have two storage region environment variables to check pod liveness and to upload content. To avaoid confusion use only one storage env
=> feat(storage): use single storage region variable

pkg/gitreceive/config.go, pkg/gitreceive/k8s_util.go
This doesn't error out if POD is not present.
Only error condition is timeout
=> feat(race): waitforpod errors out only for timeout

pkg/sshd/server.go
It's okay for connections to probe the server without initiating
a handshake, but it's still useful for developers to see when incoming
connections are not connecting.
see deis/deis#4935 for the backported fix
=> fix(pkg/sshd): demote handshake failure log to debug

pkg/gitreceive/k8s_util.go
Having same labels for every slugbuilder launch makes GC to garbage collect.
This PR fixes terminating behavior for pod. Also we haven't pin pointed the root cause for this behavior.
Listening for event stream wont help in fixing this issue.
=> feat(race): change heritage label for every pod launch

pkg/gitreceive/config.go
Set it to 15 minutes, which is the same as the Heroku default. See
https://devcenter.heroku.com/articles/slug-compiler
Fixes #205
=> fix(config.go): increase builder pod wait duration

boot.go, pkg/cleaner/cleaner.go, pkg/sshd/common_test.go, pkg/sshd/lock_test.go, pkg/sshd/server.go, pkg/sshd/server_test.go
This PR expands test coverage, mainly to the `./pkg/sshd` package. Additionally, it pulls out the cleaner locking logic to a `withCleanerLock` func in `/pkg/sshd/server.go`
Highlights of the added/improved tests:
- A test for concurrent pushes, each to a separate repository
- Improving the previously-named `TestPush` test to attempt a larger number of concurrent pushes to the same repo. This test is currently skipped (with `t.SkipNow()`) and should be enabled after #209 is merged 
- Improvements to speed up tests in `server_test.go` by removing the sleep in the SSH handler func
=> feat(server): add more tests for the SSH server

glide.lock, glide.yaml, pkg/gitreceive/build.go, pkg/gitreceive/controller.go, pkg/gitreceive/controller_test.go, pkg/gitreceive/storage/auth.go, pkg/gitreceive/storage/auth_test.go, pkg/gitreceive/storage/bucket.go, pkg/gitreceive/storage/bucket_test.go, pkg/gitreceive/storage/client.go, pkg/gitreceive/storage/endpoint.go, pkg/gitreceive/storage/endpoint_test.go, pkg/gitreceive/storage/interfaces.go, pkg/gitreceive/storage/object.go, pkg/gitreceive/storage/object_test.go, pkg/gitreceive/storage/slug_builder_info.go, pkg/gitreceive/storage/slug_builder_info_test.go, pkg/healthsrv/buckets_lister.go, pkg/healthsrv/healthz_handler.go
To support Google Cloud Storage compatibility mode, the builder must support AWS version 2 signatures. Singe the `github.com/aws/aws-sdk-go` package package doesn't support v2 signing for S3, this PR replaces that package with `github.com/minio/minio-go`, which does.
This PR also emphasizes testing related to object storage, and while necessary, that emphasis led to more changes here than strictly necessary to achieve the functionality we needed.
See below for a list of additional changes necessary to aid testing:
- `minio-go` compatible interfaces
- Mocks for each of the above interfaces
- Unit tests for most of the `func`s inside of `github.com/deis/builder/pkg/gitreceive/storage`
- More logging in the git receive hook
- New utility functions (and tests for them) on `SlugBuilderInfo`
- …
=> fix(pkg/gitreceive): replace the AWS SDK with minio-go

pkg/gitreceive/storage/object_test.go
only skip it for now. this issue does *not* fix https://github.com/deis/builder/issues/238
cc/ @smothiki
=> fix(pkg/gitreceive/storage/object_test.go): skip TestWaitForObjectMissing

README.md
Also:
- Offloads many of the installation and testing instructions to the e2e tests and the official docs
- Includes more detail on how to set up and use the development environment
- Includes details on the native `go` toolchain development environment (as an alternative to the docker based dev env)
- Adds 2016 to the copyright
Once this change is merged, I'll make similar changes on the READMEs of other repositories.
cc/ @mboersma @slack
=> docs(README.md): update docs to match beta status

pkg/gitreceive/storage/object_test.go
It _should_ be called three times, but the time of the call may cause the ticker to tick after the timer receives (and the wait call bails out). it’s guaranteed to call once, however. This issue was causing intermittent test failures in CI.
Fixes #238
=> fix(pkg/gitreceive/storage/object_test.go): adjust min number of calls to the statter

.github/PULL_REQUEST_TEMPLATE
This PR fixes the link to the commit style guidelines in the Pull Request Template file
References https://github.com/deis/workflow/issues/131
None
None
None
None. This is a documentation-only change.
=> doc(PULL_REQUEST_TEMPLATE): fix commit style guideline link

pkg/git/git.go
This PR removes the environment variable declarations from the git pre-receive hook script. When any one of the environment variables is not set in the main process, it's sent into the pre-receive hook process as the empty string, and that was leading to configuration errors in the hook, which was failing builds.
For example, if `SLUG_BUILDER_IMAGE_PULL_POLICY` was empty in the main process, it would be sent to `""` in the hook before this change. Then, the hook would try to convert `""` to a valid pull policy, which would fail, and the entire build would fail.
Fixes #293
None
None
None
1. Start a builder with no `SLUG_BUILDER_IMAGE_PULL_POLICY` or `DOCKER_BUILDER_IMAGE_PULL_POLICY` image pull policy environment variables set
2. Do a `git push` with a buildpack app
3. Do a `git push` with …
=> fix(pkg/git/git.go): fix blank image pull policy

pkg/gitreceive/build.go
This PR avoid builder to poll for object storage if the file were uploaded or not
Ref https://github.com/deis/slugrunner/pull/26
Ref https://github.com/deis/slugbuilder/pull/52
3. Your Steps Here...
Also, please provide a description of the desired result after the tester completes the above steps.
1. The app called "abcd" should be deployed
2. `kubectl get pod --namespace=abcd` should show 2 pods running
3. etc...
=> feat(storage): remove polling for object in storage

pkg/gitreceive/build.go, pkg/gitreceive/config.go, pkg/gitreceive/k8s_util.go
This PR adds and new function called progress which prints the message passed to it for every 8 seconds . This avoids session end and remote end hung up errors for builder while waiting to build or pull large images or if the network bandwidth is less. 
Closes https://github.com/deis/builder/issues/268
2. Register a build pack or any app
3. do git push deis master
Also, please provide a description of the desired result after the tester completes the above steps.
```
],
"restartPolicy": "Never",
"serviceAccountName": ""
},
"status": {}
}
waiting for the pod to come up ...
waiting for the pod to come up ...
download tar file complete
extracting tar file complete
Step 1 : FROM alpine:3.1
---> …
```
=> feat(progress):print status to avoid losing session

glide.lock, glide.yaml
use the latest deis/pkg/time which supports RFC3339
git push in builder is currently broken because of https://github.com/deis/controller/pull/637
2. deploy an app using git push deis master
3. app should be deployed properly and running
=> fix(bug): use the deis time which supports RFC3339 dates

pkg/gitreceive/k8s_util.go
Since the only reason we need to check if the pod is started or not is to stream the logs, we can add a check to see pod completed status if the pod run has completed before we started checking. 
Closes #199 
2. deploy an app
3. you should be able to successfully deploy and should not be able to reproduce the scenario mentioned in #298 
=> fix(slugbuilder): check for the succeded status while waiting for slugbuilder pod

pkg/routes.go, pkg/sshd/sshd.go, rootfs/etc/ssh/sshd_config
This PR moves the SSH private keys into a kubernetes secret such that when the builder is restarted (or destroyed), it retains the same private keys for authenticating clients.
Since the host keys are supplied by kubernetes, we no longer need to generate the host keys, so that code has also been removed.
Closes #157 
No changes required. The existing end-to-end tests ensure that the user can deploy applications to Workflow given this change. However, end-to-end won't work until deis/charts#237 is merged.
No changes required.
No design document required.
1. Create a Deis Cluster using the chart changes in deis/charts#237
2. Deploy a buildpack app (example-go)
3. Destroy the builder with `kubectl --namespace=deis destroy pod deis-builder-xxxx`
4. Deploy a second buildpack app
Originally, …
=> feat(pkg/sshd): Store private keys in kubernetes secret

Makefile
Builds the builder  `boot` binary with go 1.6.2 and compresses it directly with `upx`.  The `goupx` tool isn't needed since go 1.6 [according to its author](https://github.com/pwaller/goupx/blob/master/README.md#update-20160310).
See also https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/ for a discussion of the binary compression strategy Workflow components are also using.
=> ref(Makefile): use go 1.6.2 and compress with upx directly

boot.go, pkg/cleaner/cleaner.go, pkg/cleaner/cleaner_test.go, pkg/sshd/config.go
remove the usage of watch api and instead get the namespaces to know which apps are deleted because the watch api is flaky and also the channel gets closed too often https://github.com/kubernetes/kubernetes/issues/8700
closes #287 
https://github.com/deis/workflow-e2e/issues/182
2. deploy an app using git push 
3. check in the builder pod and the app should be present in the /home/git/ folder
4. delete the app
5. again check the builder pod and now it should not be present in the /home/git/ folder
=> fix(cleaner): remove the usage of watch api

pkg/gitreceive/controller.go, pkg/types.go
Show the error message returned from the controller instead of the response code
Closes #323 
2. Deploy a docker app without exposing any port and proc file so that the controller will raise an exception and the build fails.
3. Builder should output the error message instead of the response code
=> feat(controller):Show the error message from controller instead of response code

pkg/gitreceive/k8s_util.go
This environment variable is being introduced into the actual application build. causing libraries
like the ruby gem `hiredis` to install differently because we are affecting the build environment.
Please list the issue(s) that this PR closes, similar to the below:
closes deis/workflow#178
1. Create a Deis Cluster with this change as well as deis/slugbuilder#70
2. Deploy https://github.com/matthewrudy/ruby-env.git
The app should be deployed. Before, it should fail if using a version of `hiredis` earlier than https://github.com/redis/hiredis/pull/418, which is what matthewrudy/ruby-env demonstrates.
=> ref(k8s_util): change debugKey to DEIS_DEBUG

glide.lock, glide.yaml, pkg/cleaner/cleaner.go, pkg/gitreceive/build.go, pkg/gitreceive/k8s_util.go, pkg/healthsrv/namespace_lister.go, pkg/k8s/namespace.go, pkg/k8s/watch.go
change the k8s api version to 1.2.4 and fix the wait for pod as k8s now logs throttling requests.
Please list the issue(s) that this PR closes, similar to the below:
Closes #343 
Closes #344 
2. deploy an app with different storage backends
3. app should be deployed without any error
=> ref(k8s): update k8s api to 1.2.4

pkg/gitreceive/build.go
Updates the URL printed after a successful `git push` to https://deis.com/ instead of http://docs.deis.io/.
See deis/example-clojure-ring#5.
The output of a successful `git push` for an app should reference the above URL, not anything at deis.io.
=> docs(pkg): update help URL to https://deis.com/

pkg/sshd/lock.go, pkg/sshd/lock_test.go
Currently the builder is not unlocking the repo if the git push succeeds or fails because of which we can't do multiple releases to any app
3. do git push again or do a new release and you should succeed.
=> fix(sshd): unlock the repository when gitreceive succeeds or fails

pkg/sshd/server.go
Removes an uneeded `req.Reply` call that confused builder output during a simultaneous `git push` operation. This change was suggested by @kmala. :metal: 
We will work on capturing this behavior in an e2e test next, but it is not required to merge this. See also deis/workflow-e2e#230.
3. `git push` the app but hit Ctrl+C to interrupt `git` while it is pushing
4. Retry the `git push` operation repeatedly and observe the results
What you should see:
```
$ git push deis master
Counting objects: 96, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (74/74), done.
Writing objects: 100% (96/96), 20.84 KiB | 0 bytes/s, done.
Total 96 (delta 40), reused 45 (delta 17)
^CKilled by signal 2.
$ git push deis master
fatal: remote …
```
=> fix(server.go): don't reply false if lock fails

pkg/healthsrv/healthz_handler.go
Changes the healthcheck/readiness check internal timeout value to 10 seconds, to match the values used in the [Workflow charts](https://github.com/deis/charts/blob/master/workflow-dev/tpl/deis-controller-rc.yaml#L34).
This is one change of several that seem to ameliorate readiness check misbehavior under load. It doesn't fix the situation on its own but does seem to help.
Refs deis/workflow-e2e#215.
=> fix(pkg): set check timeouts to 10s

rootfs/Dockerfile
This environment variable is not necessary any more.
refs deis/workflow#356
=> ref(Dockerfile): remove WORKFLOW_RELEASE

pkg/conf/config.go, pkg/conf/config_test.go
The following code assumes that the file is a file, not a directory.
fixes #379
=> fix(pkg/conf): skip file if directory

pkg/conf/config.go, pkg/conf/config_test.go
This fixes the remaining problems described in #379 mentioned by @jackfrancis where the deis-builder pod enters a CrashLoop with the following error:
```
Error getting storage parameters (read /var/run/secrets/deis/objectstore/creds/..data: is a directory)`
```
The creds directory structure might look like this (at least on k8s 1.3.0):
```
drwxrwxrwt. 3 root root  200 Jul  9 14:49 .
drwxr-xr-x. 3 root root 4.0K Jul  9 14:50 ..
drwxr-xr-x. 2 root root  160 Jul  9 14:49 ..7987_09_07_14_49_31.664629063
lrwxrwxrwx. 1 root root   31 Jul  9 14:49 ..data -> ..7987_09_07_14_49_31.664629063
lrwxrwxrwx. 1 root root   16 Jul  9 14:49 accesskey -> ..data/accesskey
lrwxrwxrwx. 1 root root   21 Jul  9 14:49 builder-bucket -> ..data/builder-bucket
lrwxrwxrwx. 1 root root   22 Jul  9 14:49 …
```
=> fix(pkg/conf): skip ..data symlink reading creds

pkg/gitreceive/build.go, pkg/gitreceive/config.go, pkg/gitreceive/k8s_util.go, pkg/gitreceive/k8s_util_test.go
Pass the registry proxy port to docker builder.
depends this depends on 
https://github.com/deis/controller/pull/866
https://github.com/deis/dockerbuilder/pull/78
https://github.com/deis/charts/pull/305
https://github.com/deis/workflow/pull/370
1. Create a Deis Cluster without insecure regsitry settings
2. Register an dockerfile app
3. the dockerfile app should work fine
=> feat(registry): use registry proxy to talk to the internal registry

rootfs/Dockerfile
Copy the code/binaries after installing the required packages to cache during docker build in development environment.
=> ref(dockerfile): Copy the code contents after installing required packages

pkg/gitreceive/build.go, pkg/gitreceive/config.go, pkg/gitreceive/k8s_util.go, pkg/gitreceive/k8s_util_test.go
Dockerbuilder fails pushing images to the registry when --insecure-registry
is turned off because it is not using the registry proxy to push images.
closes https://github.com/deis/dockerbuilder/issues/83
=> fix(k8s_util): proxy registry host/port information to dockerbuilder

pkg/gitreceive/build.go, pkg/gitreceive/k8s_util.go, pkg/gitreceive/k8s_util_test.go, pkg/gitreceive/slug_builder_info.go, pkg/gitreceive/slug_builder_info_test.go
Allows the slugbuilder to persist cache between deploys. `CACHE_PATH` is
not specific to a certain deploy, and doesn't contain the commit hash.
refs deis/slugbuilder#99
=> feat(slugbuilder-cache): Add CACHE_PATH variable

README.md
Fixes the currently "unknown" badge status by updating to what codecov.io suggests at https://codecov.io/gh/deis/builder/settings/badge.
=> fix(README.md): correct coverage badge URL

pkg/gitreceive/k8s_util_test.go
Before, we didn't test if the CACHE_PATH was defined properly.
=> test(slugbuilder-cache): add missing test for CACHE_PATH

pkg/gitreceive/k8s_util_test.go
In the refactor of 67a9adbf9a7f18794106868065a06282c0dda1b6, some things were changed along with these tests, but they were never deduplicated. This should get these out.
=> tests(gitreceive): remove duplicated tests

pkg/gitreceive/k8s_util.go, pkg/gitreceive/k8s_util_test.go
When the slugbuilder doesn't receive a `CACHE_PATH`, it'll skip caching. Adding `DEIS_DISABLE_CACHE` config variable will disable the cache and will not define `CACHE_PATH` on the slugbuilder pod, preventing it from reading/writing cache.
=> feat(slugbuilder-cache): allow turning caching off completely

.travis.yml
caching the vendor directory has caused more headaches than actual improvements to CI. Removing the vendor dir from being cached should save us any issues with CI in the future.
refs https://github.com/deis/builder/issues/438
ping @kmala
=> fix(travis): remove vendor dir from cache

glide.lock, glide.yaml
Fixes a double-slash in the /healthz controller URL. See deis/controller-sdk-go#103.
=> chore(glide.yaml): update controller-sdk-go

boot.go, pkg/cleaner/cleaner.go, pkg/gitreceive/slug_builder_info.go
The cleaner now deletes slug and cache files from object storage as well as locally. I didn't write any tests I'm not sure the best way to attempt to mock the object store driver and the cleaner function is untested.
I'm happy to write tests if you have pointers to ways to go about mocking the storage driver.
Fixes #214
=> feat(cleaner): delete from object store

glide.lock, glide.yaml
=> chore(glide): bump golang.org/x/crypto to b822463

charts/builder/templates/builder-deployment.yaml
On some providers, "localhost" is not set up on the host network. explicitly calling the loopback
address fixes this.
See deis/workflow#678
=> fix(charts): reference registry-proxy on 127.0.0.1

rootfs/Dockerfile
I'm still running into issues with `make docker-build` locally. This fixes it.
=> fix(Dockerfile): force gunzip of license files

.travis.yml
Without this change, Travis CI runs a separate [job for each environment variable](https://docs.travis-ci.com/user/environment-variables/#Defining-Multiple-Variables-per-Item), which was unintended.
=> fix(.travis.yml): declare env vars on one line

glide.lock, glide.yaml
See https://github.com/golang/crypto/compare/b82246307bd525fde15c1df976318003716bca68...453249f01cfeb54c3d549ddb75ff152ca243f9d8
Refs #462.
=> chore(glide): bump golang.org/x/crypto to 453249f

charts/builder/templates/builder-deployment.yaml, charts/builder/values.yaml, pkg/gitreceive/build.go, pkg/gitreceive/build_test.go, pkg/gitreceive/config.go, pkg/gitreceive/k8s_util.go, pkg/gitreceive/k8s_util_test.go
add a new environment variable to inject builder job node selector.
format `BUILDER_POD_NODE_SELECTOR` = `network:fast,disk:ssd`
Closes https://github.com/deis/builder/issues/410
docs https://github.com/deis/workflow/pull/770
=> Add pod selector for builder job

pkg/gitreceive/k8s_util_test.go
val != val is clearly never going to fail. Changed
to expVal != val
=> fix(gitreceive): fix checkForEnv logic

pkg/gitreceive/config.go
=> Fix ObjectStorageTickDurationMSec envconfig typo

pkg/gitreceive/k8s_util.go, pkg/gitreceive/k8s_util_test.go
injecting build args into the image by default has caused a significant performance penalty for
applications not utilizing the build args. Making it an opt-in feature flag via `deis config:set DEIS_DOCKER_BUILD_ARGS_ENABLED=1` allows users to inject their environment into their Dockerfiles, but they must opt into that performance penalty.
I feel like there's been enough concerns about turning this feature flag on by default in v2.12.0 that we should consider cutting a v2.12.1 with this fix.
=> ref(k8s_util): make users opt into DOCKER_BUILD_ARGS

pkg/gitreceive/k8s_util.go, pkg/gitreceive/k8s_util_test.go
kubernetes has a name length limit of 63 characters. We must truncate the name such that it stays
below that limit with the new app name length bump.
closes #504
=> fix(builder): truncate slugbuilder and dockerbuilder pod name length

charts/builder/templates/_helpers.tmpl, charts/builder/templates/builder-clusterrole.yaml, charts/builder/templates/builder-clusterrolebinding.yaml, charts/builder/templates/builder-role.yaml, charts/builder/templates/builder-rolebinding.yaml, charts/builder/values.yaml
With this change deis-builder became available to work in **RBAC**-only clusters
Works with both Kubernetes 1.5 and 1.6 (see `templates/_helpers.tmpl` for details)
Actually tested with 1.5.7 and 1.6.2
Role allows `deis-builder`:
- `secrets`: `create`, `update` and `delete`
- `pods`: `get`, `list`, `watch` and `create`
- `pods/log:` `get`
ClusterRole allows `deis-builder`:
- `namespaces`: `list`
=> RBAC support

pkg/sshd/server.go
RC4 Ciphers are known to be weaker. This PR removes them, leaving all other default ciphers in place. https://www.rfc-editor.org/rfc/rfc7465.txt
=> fix(builder): Remove RC4 Ciphers
