deis/builder

.gitignore, Makefile, glide.yaml, pkg/builder.go
=> chore(*): vendoring all dependencies

.travis.yml, Makefile, _scripts/deploy.sh, manifests/deis-builder-rc.yaml
Minimal CD automation in order to facilitate testing of Deis v2.
=> feat(deploy.sh): push deisci/builder:v2-alpha images from master

manifests/deis-builder-service.yaml, rootfs/etc/confd/templates/builder
Previously we are just checking procfile present and falling back to dockerfile and not checking if dockerfile is also present.
The new condition will extract the git archive to temp dir and checks for procfile or dockerfile.
=> fix(builder): add check to locate Procfile

manifests/deis-builder-rc.yaml, manifests/deis-builder-service.yaml, rootfs/etc/deis-dockerbuilder.yaml, rootfs/etc/deis-slugbuilder.yaml
also remove errant comments and set versions to proper values
replaces part of #9
=> fix(manifests): mount and use auth secrets correctly and use proper image names

pkg/confd/confd.go, pkg/etcd/etcd.go, pkg/git/git.go, pkg/sshd/server.go, rootfs/etc/confd/templates/builder
=> feat(*): add support for uploading tarballs to minio

rootfs/etc/confd/templates/builder, rootfs/etc/confd/templates/receiver
Ref deis/workflow#58
Are the workflow hooks used anywhere else?
=> fix(builder): use workflow v2 hook urls

README.md
=> doc(README.md): add basic documentation

manifests/deis-builder-rc.yaml, rootfs/etc/confd/templates/builder
=> fix(*): use alpine linux compatible mc binary

manifests/deis-builder-rc.yaml, rootfs/etc/confd/templates/builder
=> fix(deis-builder-rc.yaml,builder): create builder pods in correct namespace

README.md
=> doc(README.md): show badge for, and link to builder build (instead of minio build)

rootfs/etc/confd/templates/builder
Only do so when builder is configured to upload to remote storage.
Fixes #45 
Fixes #49
=> fix(builder): ping remote storage to determine when builds are done

Dockerfile, rootfs/Dockerfile
Fixes part of https://github.com/deis/workflow/issues/97
cc/ @mboersma
=> chore(Dockerfile): update version

Makefile
Travis should have caught this in previous PRs. I'll be investigating and opening a a subsequent PR if necessary.
=> fix(Makefile): set GO15VENDOREXPERIMENT in the build container

pkg/src/get-app-config.go, rootfs/etc/confd/templates/builder, rootfs/etc/deis-slugbuilder.yaml
Added buildpack url environment variable to slugbuilder template
=> feat(builder): add support for custom buildpack url

rootfs/etc/confd/templates/builder
Modify dockerbuilder and slugbuilder templates if the secret is not present.
=> feat(builder): adjust dockerbuilder and slugrunner templates

rootfs/Dockerfile
docker builds are slightly faster this way
=> fix(Dockerfile): merging 2 apk commands

pkg/gitreceive/build.go
=> fix(build.go): add informational message for cold builds

glide.lock, glide.yaml, pkg/types.go, pkg/utils_test.go
replace the one place it was used with github.com/deis/pkg
Fixes #75
=> fix(*): remove dependency on github.com/deis/deis

Makefile, glide.lock, glide.yaml
- flatten deps
- remove unneeded top level deps
- ignore appengine cruft
- specify a package name
=> fix(glide.yaml): clean up dependency list

Makefile, glide.yaml, pkg/gitreceive/build.go, pkg/gitreceive/build_type.go, pkg/gitreceive/build_type_test.go
=> fix(Makefile,build.go,build_type.go,build_type_test.go): choose slug builds by default, unless a Dockerfile is present

boot.go, pkg/gitreceive/build.go, pkg/gitreceive/config.go, pkg/gitreceive/config_test.go
=> feat(builder): make the builder pod timeout configurable

pkg/gitreceive/build.go, pkg/gitreceive/k8s_util.go, pkg/gitreceive/storage/slug_builder_info.go, pkg/gitreceive/storage/slug_builder_info_test.go
build fucntion supports dockerfile builder.
was able to launch the POD but because of readiness probe unable to start the container, which is not related to build logic and should be fixed from workflow end.
will Open an issue in workflow.
=> feat(dockerbuilder): add logic to build dockerfile builds

README.md
=> doc(README.md): add container badge to README

pkg/gitreceive/k8s_util.go
fixes https://github.com/deis/builder/issues/142
=> fix(builder): change dockerfile builder image

pkg/controller/utils.go, pkg/git/git.go
=> ref(builder): fix capitalization

Makefile
=> ref(makefile): update go-dev to 0.5.0

rootfs/Dockerfile
=> ref(rootfs/Dockerfile): upgrade to alpine 3.3, clean up the dockerfile

pkg/gitreceive/build.go, pkg/gitreceive/k8s_util.go
This avoid the creation of new releases that will end in a `CrashLoopBackoff` status
=> fix(builder): if exit code from build pod is not 0 it must return an error

.travis.yml, Makefile, rootfs/Dockerfile
This PR allows us to test Dockerfile changes in PRs
Fixes #169
=> fix(.travis.yml): run the docker-build target on all branches

pkg/gitreceive/storage/bucket.go
=> fix(gitreceive/storage/bucket.go): silence bucket creation errors

pkg/sshd/lock.go, pkg/sshd/lock_test.go, pkg/sshd/server.go, pkg/sshd/server_test.go
```
$ git push deis master
fatal: remote error: Another git push is ongoing. Aborting...
exec request failed on channel 0
```
closes #168
=> bug(builder): avoid simultaneous git push

Makefile, glide.lock
this includes glide version 0.9
=> chore(Makefile): upgrade the go-dev image to 0.8.0

pkg/gitreceive/build.go, pkg/gitreceive/config.go, pkg/gitreceive/k8s_util.go, pkg/gitreceive/k8s_util_test.go, pkg/gitreceive/storage/slug_builder_info.go, pkg/gitreceive/storage/slug_builder_info_test.go
Make root bucket configurable. defaults to /git
=> feat(storage): configure bucket name

pkg/gitreceive/config.go
resetting this back to 0.1s as the tests got much worse
=> fix(timeout): reset pod tick timeout duration to 0.1s

pkg/gitreceive/build.go
=> fix(pkg/gitreceive/build.go): change err message to indicate code for failed build pods

boot.go, pkg/gitreceive/build.go, pkg/gitreceive/run.go, pkg/gitreceive/storage/auth.go, pkg/gitreceive/storage/auth_test.go, pkg/gitreceive/storage/client.go, pkg/gitreceive/storage/client_test.go, pkg/gitreceive/storage/endpoint.go, pkg/gitreceive/storage/endpoint_test.go, pkg/sys/env.go, pkg/sys/fs.go
This PR creates interfaces meant for interacting with environment variables and for reading from the filesystem. Various pieces of the storage package use these interfaces, and this PR also adds mock implementations of those interfaces and unit tests for the aforementioned pieces.
Fixes #227 
TODO:
=> fix(*): creating and using interfaces for system tasks

pkg/gitreceive/build.go
dont poll S3 storage if build pack type is dockerfile
=> fix(storagepoll): dont poll s3 for slugfile if app type is dockerfile

Makefile, pkg/gitreceive/build.go, pkg/gitreceive/build_test.go, pkg/gitreceive/storage/interfaces.go, pkg/gitreceive/storage/object.go, pkg/gitreceive/storage/object_test.go, pkg/gitreceive/storage/slug_builder_info.go
=> fix(procfile): get the procfile from the slug if not present

pkg/gitreceive/build.go, pkg/gitreceive/config.go, pkg/gitreceive/k8s_util.go, pkg/gitreceive/k8s_util_test.go
fixes #66 
*Update by mboersma*:
Closes deis/workflow#135.
Closes deis/workflow#323.
=> feat(builder): get the slug/docker builder images from the environment

boot.go, pkg/cleaner/cleaner.go, pkg/cleaner/cleaner_test.go, pkg/sys/fs.go
Little tricky as my first run got hung up at watching events at the channel
Working more on this.
=> feat(cleaner): write unit test for cleaner 

Makefile
=> chore(Makefile): upgrade the go-dev image to 0.9.1

README.md, pkg/conf/config.go, pkg/controller/utils.go, pkg/gitreceive/config.go, pkg/gitreceive/controller.go, pkg/gitreceive/storage/slug_builder_info.go
this broke with the change in https://github.com/deis/charts/pull/153
=> fix(pkg): rename workflow to controller

pkg/builder.go, pkg/cleaner/cleaner.go, pkg/conf/config.go, pkg/controller/utils.go, pkg/git/git.go, pkg/gitreceive/build.go, pkg/gitreceive/config.go, pkg/gitreceive/git/sha.go, pkg/gitreceive/run.go, pkg/gitreceive/storage/auth.go, pkg/gitreceive/storage/bucket.go, pkg/gitreceive/storage/client.go, pkg/gitreceive/storage/endpoint.go, pkg/gitreceive/storage/interfaces.go, pkg/gitreceive/storage/object.go, pkg/gitreceive/storage/slug_builder_info.go, pkg/healthsrv/buckets_lister.go, pkg/healthsrv/circuit_state.go, pkg/healthsrv/healthz_handler_test.go, pkg/healthsrv/namespace_lister.go, pkg/healthsrv/server.go, pkg/k8s/namespace.go, pkg/sshd/circuit.go, pkg/sshd/common_test.go, pkg/sshd/config.go, pkg/sshd/lock.go, pkg/sshd/server.go, pkg/sys/env.go, pkg/sys/fs.go
Also:
- Ensure that comments (including godoc comments, but _not_ code) don't expand beyond the 99 character limit described in the [code standards](http://docs.deis.io/en/latest/contributing/standards/#code-standards)
- Fix some small grammatical issues in docs
- Ensure that all godoc documentation is written with complete sentences
Fixes #230
=> fix(*): add godocs and address other golint issues

README.md
=> doc(README.md): remove article preceding proper noun

README.md
=> doc(README.md): modify the introductory text

pkg/gitreceive/k8s_util.go
This PR adds a check for an error that was previously unchecked in the implementation of `waitForPodCondition`
None
None required
None required
None required
Simply run `make test` on your local machine. All tests should pass.
=> fix(k8s_util.go): check pod condition error

Makefile
make docker-build call build
Jenkis use a common script to build an image out of the PR and run e2e tests https://github.com/deis/jenkins-jobs/blob/master/jobs/component_jobs.groovy#L101-L113
fixes #285 
1. Do make docker-build docker-push 
2. Use the above image deploy deis cluster
3. deploy an app and it should work fine
=> fix(makefile): make the docker-build call the build

pkg/cleaner/cleaner.go
This PR fixes the issue builder taking high CPU by waiting on the channel stream using select.
Fixes #280 
After the fix:
```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O
5be5bad7ce1a        0.32%               22.45 MB / 3.892 GB   0.58%               0 B / 0 B           0 B / 0 B
```
Testing: 
2. Deploy an App
3. Destroy the App
4. Check the /home/git/ folder and it shouldn't contain the created app git repo
=> fix(cleaner): builder taking high CPU

CHANGELOG.md, _scripts/generate-changelog.sh
Adds a markdown CHANGELOG.md and the script to generate it, copied from deis/deis.
=> feat(_scripts): add CHANGELOG.md and generator script

CHANGELOG.md
=> chore(changelog): update the changelog for the beta2

.github/PULL_REQUEST_TEMPLATE
This PR changes the links from deis/docs-v2 to deis/workflow.
=> fix(.github): rename docs-v2 to workflow

pkg/sshd/server.go
=> fix(sshd): log incoming env request to debug level

pkg/gitreceive/build.go
=> feat(gitreceive): remove tmp build dir on success

CHANGELOG.md
Updates CHANGELOG.md with beta3 changes.
=> docs(CHANGELOG.md): update for v2.0.0-beta3

pkg/git/git.go
make sure the errors are not suppressed when output is piped allowing successive pushes without a dummy commit.
2. deploy a app which errors out.
3. git push should fail saying remote rejected meaning you should be able to do another git push without a dummy commit.
=> fix(git-push):handle the errors during git push

pkg/gitreceive/build.go
=> fix(gitreceive): ignore error if `git gc` fails

pkg/gitreceive/k8s_util.go
remove the default case inside a select in an empty for loop as it does nothing and might cause high spu usage during git push 
2. Deploy an app
3. It should work fine
=> ref(progress): remove unused default select case in an empty for loop

pkg/healthsrv/healthz_handler.go, pkg/healthsrv/healthz_handler_test.go, pkg/healthsrv/readiness_handler.go, pkg/healthsrv/server.go
move the k8s api check to readiness probe
2. Deploy an app successfully
=> ref(probes): move k8s probe from liveness into readiness

Makefile, rootfs/Dockerfile
Updated `DEIS_RELEASE` to be `WORKFLOW_RELEASE` as done similarly elsewhere (see https://github.com/deis/workflow/pull/193)
=> chore(Makefile,Dockerfile): DEIS_RELEASE -> WORKFLOW_RELEASE

pkg/controller/utils.go, pkg/healthsrv/controller_state.go, pkg/healthsrv/healthz_handler_test.go, pkg/healthsrv/readiness_handler.go, pkg/healthsrv/server.go
add probe to check the status of the controller
Closes #181 
2. check the status of the builder and it should be serving
3. now stop the controller and check the status of the builder, it should still be up but not ready to serve requests
=> feat(probes): add controller check to the readiness probe

glide.lock, glide.yaml, pkg/gitreceive/build.go
Current behavior:
```
Build complete.
...
...
...
...
...
...
...
...
Launching App...
Done, mellow-nonesuch:v6 deployed to Deis
Use 'deis open' to view this application in your browser
```
=> style(release): tell the user we are releasing before we do it

CHANGELOG.md
=> feat(changelog): update changelog to v2.0.0-rc1

pkg/gitreceive/build.go, pkg/gitreceive/build_test.go
check for procfile for all type of apps
Closes #342 
see #342 for detailed instructions
=> fix(proctype):deploy dockerfile app with procfile

boot.go, pkg/sshd/config.go, pkg/sshd/lock.go, pkg/sshd/lock_test.go, pkg/sshd/server.go, pkg/sshd/server_test.go
This PR implements a lock timeout. Where you can do git push again if the on going git push timeouts 
3. Your Steps Here...
Also, please provide a description of the desired result after the tester completes the above steps.
1. The app called "abcd" should be deployed
2. `kubectl get pod --namespace=abcd` should show 2 pods running
3. etc...
=> feat(lock): add timeout to repository lock feature

README.md
Docs change in `README.md` and defaults change in `pkg/gitreceive/config.go`.
Ref deis/workflow#285
=> chore(various): remove beta status

boot.go, glide.lock, glide.yaml
Add support to support swift storage
refer https://github.com/deis/workflow/issues/306
Ref https://github.com/deis/workflow/issues/306
2. Register an app using swift as storage
3. The app should work fine.
=> feat(swift): Add support for swift object storage

boot.go, pkg/README.md, pkg/gitreceive/config.go
check for DEIS_DEBUG as this is the one set in the charts.
1. Create a Deis Cluster with DEIS_DEBUG falg set to true in the charts
3. you should see the debug output
=> fix(flag):Use DEIS_DEBUG instead DEBUG environment variable for debug settings

rootfs/.dockerignore, rootfs/Dockerfile
closes #362 
closes deis/deis#5031
=> chore(Dockerfile): bump git to v2.8.4

pkg/gitreceive/k8s_util.go
=> fix(pod): log pod error status and message instead of pod struct

boot.go, pkg/builder.go, pkg/conf/config.go, pkg/conf/config_test.go, pkg/controller/utils.go, pkg/controller/utils_test.go, pkg/gitreceive/build.go, pkg/gitreceive/run.go, pkg/healthsrv/server.go, pkg/sshd/config.go, pkg/sshd/server.go
=> ref(controller): use the env config instead of directly getting from environment

pkg/sshd/lock.go
=> fix(sshd): Typo in the timeout message.

boot.go, glide.lock, glide.yaml, pkg/conf/config.go, pkg/conf/config_test.go, pkg/controller/utils.go, pkg/controller/utils_test.go, pkg/gitreceive/build.go, pkg/gitreceive/build_test.go, pkg/gitreceive/run.go, pkg/gitreceive/run_test.go, pkg/healthsrv/server.go, pkg/sshd/server.go, pkg/storage/image_repo.go, pkg/storage/image_repo_test.go, pkg/storage/object_test.go, pkg/sys/env_test.go, pkg/sys/fs_test.go
Using this PR along with codecov to display how much of the codebase is covered as I go along.
closes #436
=> tests(pkg): beef up unit tests

Makefile, rootfs/Dockerfile
See https://github.com/deis/docker-base/releases/tag/v0.3.5
and https://github.com/deis/docker-go-dev/releases/tag/0.20.0
=> chore(Makefile,Dockerfile): update base and go-dev to latest

pkg/gitreceive/build.go, pkg/gitreceive/k8s_util.go, pkg/gitreceive/k8s_util_test.go, pkg/gitreceive/registry.go, pkg/gitreceive/registry_test.go, pkg/k8s/secrets.go
=> fix(slugbuilder): Dont expose the config as env vars during build

charts/builder/templates/builder-deployment.yaml
ref https://github.com/deis/dockerbuilder/pull/107 and https://github.com/deis/slugbuilder/pull/123
=> fix(charts): Don't use caps in the configmap keys

README.md
=> docs(*): Fix typo in README.md

Makefile, pkg/conf/config.go, pkg/gitreceive/build.go, pkg/gitreceive/slug_builder_info.go, pkg/sys/fs_test.go
See https://github.com/deis/docker-go-dev/releases/tag/v0.22.0
=> chore(Makefile): update docker-go-dev to v0.22.0

pkg/gitreceive/build.go
=> fix(gitreceive/build.go): watch pods in the appropriate namespace

pkg/gitreceive/k8s_util.go
=> Fix for #478

charts/builder/templates/builder-secret-ssh-private-keys.yaml, pkg/sshd/server.go, rootfs/etc/ssh/sshd_config
Ref https://github.com/golang/go/issues/19424
A ~~potential~~ fix/solution for https://github.com/deis/builder/issues/462 ~~(need further testing/deployment into clusters to be sure)~~
=> ref(ssh keys): remove support for DSA
